### ISSUE TITLE
Package maintainer and new app

### ISSUE THREAD

**Issue by lucasvdh** [kruimel0/yamaha-app-homey#20]
@kruimel0 would you be interested in making me the primary maintainer of the Yamaha app?

[I've written a new Yamaha app](https://github.com/lucasvdh/com.yamaha.receiver) based on this one which takes care of some bugs that are still present in this version and the overall code quality has been improved. These changes could either be merged in this repository or you could make me the maintainer of the Homey app and then I could update the app from the other repository.
This is because [Athom doesn't want multiple apps for the same brand/device](https://apps.developer.athom.com/tutorial-App%20Store.html). If you'd like to stay the primary maintainer, that's fine by me as well, but then I do think that I will frequently require something from you in the coming month(s) while I'm working on the new app.

Let me know what you decide.

**Comment by kjamartens** [comment]
Hi Lucas,

I'd love to make you the primary maintainer. Thank you a lot for re-writing the app - I'm sure it'll be better than how I've written it. I simply don't have the time or energy to improve it anymore.

Anyhow, do you have any idea how I can make you primary maintainer? I'll look around a bit on the app store and in github in the mean time.

Koen

**Comment by kjamartens** [comment]
@lucasvdh The only things I can find is that I update the Yamaha app on the Homey app store with your new github link, and ask Athom directly (via the developer page) to switch main developer from me to you. Do you think that's the best way forward?

Please let me know - also if your github version of the yamaha app is stable enough to be released on the Homey app page.

**Comment by lucasvdh** [comment]
@kjamartens thanks for responding. 

I was wondering the same. I think it is possible for Athom to switch the maintainer of an app because I once read Emile Nijssen transferred an app to someone else, but it's probably not possible for non-employees. The best option is most likely to submit a support ticket with this request. I've also asked this question in Athom's Slack community, I'll post any updates here.

#### Regarding the stability of the new app
I'm still testing an alpha version of my app and fixing bugs I come across. However, it might take a bit longer before I'd want to release something on a beta channel because I'm considering another re-write. 

I found out that Yamaha amplifiers offer a lot more functionality accessible via the UPnP standard. Features like; more fine grained control over playing items from radio/usb/spotify/etc, reading data like the active track/artist and playing an audio or video stream.

**Comment by lucasvdh** [comment]
Confirmed, to transfer ownership of an app, just submit a support ticket with this request.

If you request this now, I will just leave the current app as is until I've got a tested and stable version. I will also be able to submit a new alpha version of the app and point that to my repository. That would make it easier for me to invite a larger user base for closed alpha testing.

**Comment by lucasvdh** [comment]
@kjamartens did you find the time yet to sumbit a support ticket to Athom? When requesting the ownership transfer request, you can refer to me via my email address ([lucasvdhave@gmail.com](mailto:lucasvdhave@gmail.com)), that should be known at Athom.

**Comment by kjamartens** [comment]
Yes I've contacted Athom. I've included your github and Athom forum account tags, not your email :)

No response yet.

**Comment by lucasvdh** [comment]
Awesome, thanks for the effort :+1: I will patiently await their response.

**Comment by lucasvdh** [comment]
Transfer complete :tada:
